name: CI
on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.ref_name != 'main' || github.sha }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - args: [--frozen-lockfile]
          standalone: true
      
      - name: Install dependencies with frozen lockfile
        run: pnpm install --frozen-lockfile
        continue-on-error: true
      
      - name: Fix patch mismatch
        if: failure()
        run: |
          echo "Fixing patch mismatch..."
          # Remove invalid patches
          jq 'del(.patchedDependencies["@jupyterlab/codeeditor"]) | del(.patchedDependencies["@jupyterlab/shared-models"])' package.json > package_temp.json
          mv package_temp.json package.json
          pnpm install --no-frozen-lockfile

      - name: Commit updated package.json and lockfile
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json pnpm-lock.yaml
          git commit -m "fix: resolve patch mismatch"
          git push
      
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files
      
      - name: Build the project
        run: pnpm build
